---
Name: shop-multicurrency
After:
  - silvershop/config#shopconfig
---
#
# Product Currencies settings
#
Currency:
  currency_symbol: '' # Reset default $
ProductMultiCurrency:
  default_currency: 'USD'
#  domains:
    #local server
    #mysite.dev:
    #  currencies:
    #    - USD
    #    - EUR
    #test server
    #mysite.test.com:
    #  currencies:
    #    - USD
    #    - EUR
    #live server
    #mysite.com:
    #  currencies:
    #    - USD
    #    - EUR


Product:
  extensions:
    - SilverShop\MultiCurrency\Extensions\ProductMultiCurrencyExtension

ProductVariation:
  extensions:    
    - SilverShop\MultiCurrency\Extensions\ProductMultiCurrencyExtension

Order:
  extensions:
    - SilverShop\MultiCurrency\Extensions\OrderExtension

## Silvershop Orderprocessor does not have any hooks for changing currency
## So we have to replace it
Injector:
  OrderProcessor:
    class: SilverShop\MultiCurrency\Checkout\OrderProcessor