#
# Product Currencies settings
#
Currency:
  currency_symbol: '' # Reset default $
ProductMultiCurrency:
  default_currency: 'USD'
#  domains:
    #local server
    #mysite.dev:
    #  currencies:
    #    - USD
    #    - EUR
    #test server
    #mysite.test.com:
    #  currencies:
    #    - USD
    #    - EUR
    #live server
    #mysite.com:
    #  currencies:
    #    - USD
    #    - EUR


Product:
  extensions:
    - SilverShop\MultiCurrency\ProductMultiCurrency

ProductVariation:
  extensions:    
    - SilverShop\MultiCurrency\ProductMultiCurrency

Order:
  extensions:
    - SilverShop\MultiCurrency\OrderExtension